### model
model_name_or_path: /home/xiaoman/project/gec/HandwrittenGEC/gectoolkit/llm/LLaMA-Factory/models/qwen2-7b-visual-text/  #modify

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: Grammar_error_train    # modify
template: qwen                # modify
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2-7b-visual-text-grammar/lora/sft    # modify
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
